### ISSUE TITLE
Element 'argument': This element is not expected.

### ISSUE THREAD

**Issue by harendraprajapati** [magepow/magento2-sizechart#1]
Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/app/code/Magepow/Sizechart/view/adminhtml/ui_component/magepow_sizechart_sizechart_listing.xml" is invalid:
Element 'argument': This element is not expected. Expected is one of ( settings, action, actionDelete, actions, actionsColumn, bookmark, boolean, button, checkbox, checkboxset ).
Line: 45

**Comment by magiccart** [comment]
@harendraprajapati We have fixed it, please check again.

**Comment by sanojyadav** [comment]
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "C:/xampp/htdocs/magento2/app/code/Custom/Blog/view/adminhtml/ui_component/customblog_new_form.xml" is invalid:
Element 'argument': This element is not expected. Expected is one of ( aclResource, dataProvider ).
Line: 23

Verify the XML and try again.

Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "C:/xampp/htdocs/magento2/app/code/Custom/Blog/view/adminhtml/ui_component/customblog_new_form.xml" is invalid:
Element 'argument': This element is not expected. Expected is one of ( aclResource, dataProvider ).

**Comment by sanojyadav** [comment]
please helep
here is my xml form


<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <argument name="data" xsi:type="array">
        <item name="js_config" xsi:type="array">
            <item name="provider" xsi:type="string">customblog_new_form.customblog_form_data_source</item>
            <item name="deps" xsi:type="string">customblog_new_form.customblog_form_data_source</item>
        </item>
        <item name="label" xsi:type="string" translate="true">Add / Edit Post</item>
        <item name="config" xsi:type="array">
            <item name="dataScope" xsi:type="string">data</item>
            <item name="namespace" xsi:type="string">customblog_form</item>
        </item>
        <item name="template" xsi:type="string">templates/form/collapsible</item>
        <item name="buttons" xsi:type="array">
            <item name="save" xsi:type="string">Custom\Blog\Block\Adminhtml\Edit\Button\Save</item>
            <item name="delete" xsi:type="string">Custom\Blog\Block\Adminhtml\Edit\Button\Delete</item>
        </item>
    </argument>
    <dataSource name="customblog_form_data_source">
        <settings>
            <submitUrl path="customblog/post/savepost"/>
        </settings>
        <argument name="dataProvider" xsi:type="configurableObject">
            <argument name="class" xsi:type="string">Custom\Blog\Model\DataProvider</argument>
            <argument name="name" xsi:type="string">customblog_form_data_source</argument>
            <argument name="primaryFieldName" xsi:type="string">post_id</argument>
            <argument name="requestFieldName" xsi:type="string">id</argument>
        </argument>
        <argument name="data" xsi:type="array">
            <item name="js_config" xsi:type="array">
                <item name="component" xsi:type="string">Magento_Ui/js/form/provider</item>
            </item>
        </argument>
    </dataSource>
    <fieldset name="customblog_new_form">
        <argument name="data" xsi:type="array">
            <item name="config" xsi:type="array">
                <item name="collapsible" xsi:type="boolean">false</item>
                <item name="label" xsi:type="string" translate="true">Add / Edit Post</item>
                <item name="sortOrder" xsi:type="number">20</item>
            </item>
        </argument>
         <field name="post_id">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="dataType" xsi:type="string">text</item>
                    <item name="label" xsi:type="string" translate="true">Name</item>
                    <item name="formElement" xsi:type="string">input</item>
                    <item name="source" xsi:type="string">customblog_form</item>
                    <item name="dataScope" xsi:type="string">post_id</item>
                </item>
            </argument>
             <settings>
                      <visible>false</visible>
             </settings>
        </field>
        <field name="name">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="dataType" xsi:type="string">text</item>
                    <item name="label" xsi:type="string" translate="true">Name</item>
                    <item name="formElement" xsi:type="string">input</item>
                    <item name="source" xsi:type="string">customblog_form</item>
                    <item name="dataScope" xsi:type="string">name</item>
                </item>
            </argument>
        </field>
        <field name="url_key">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="dataType" xsi:type="string">text</item>
                    <item name="label" xsi:type="string" translate="true">Url key</item>
                    <item name="formElement" xsi:type="string">input</item>
                    <item name="source" xsi:type="string">customblog_form</item>
                    <item name="dataScope" xsi:type="string">url_key</item>
                </item>
            </argument>
        </field>
        <field name="post_content">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="dataType" xsi:type="string">text</item>
                    <item name="label" xsi:type="string" translate="true">Post Content</item>
                    <item name="formElement" xsi:type="string">textarea</item>
                    <item name="source" xsi:type="string">customblog_form</item>
                    <item name="dataScope" xsi:type="string">post_content</item>
                </item>
            </argument>
        </field>
    </fieldset>
</form>

**Comment by sanojyadav** [comment]
issue with this 

<settings>
            <submitUrl path="customblog/post/savepost"/>
        </settings>


when i commented this line error not showing. but data not saving in table.
