### ISSUE TITLE
error Magento 2.4.5 php8.1

### ISSUE THREAD

**Issue by ticbitvax** [magepow/magento2-sizechart#3]
{"0":"Class Magepow\\Sizechart\\Model\\sizechart does not exist","1":"#1 Magento\\Framework\\Code\\Reader\\ClassReader->getConstructor() called at [vendor\/magento\/framework\/ObjectManager\/Definition\/Runtime.php:54]\n#2 Magento\\Framework\\ObjectManager\\Definition\\Runtime->getParameters() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:100]\n#3 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:56]\n#4 Magento\\Framework\\ObjectManager\\ObjectManager->create() called at [generated\/code\/Magepow\/Sizechart\/Model\/sizechartFactory.php:43]\n#5 Magepow\\Sizechart\\Model\\sizechartFactory->create() called at [app\/code\/Magepow\/Sizechart\/Controller\/Adminhtml\/Sizechart\/AddRow.php:29]\n#6 Magepow\\Sizechart\\Controller\\Adminhtml\\Sizechart\\AddRow->execute() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#7 Magepow\\Sizechart\\Controller\\Adminhtml\\Sizechart\\AddRow\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#8 Magepow\\Sizechart\\Controller\\Adminhtml\\Sizechart\\AddRow\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#9 Magepow\\Sizechart\\Controller\\Adminhtml\\Sizechart\\AddRow\\Interceptor->___callPlugins() called at [generated\/code\/Magepow\/Sizechart\/Controller\/Adminhtml\/Sizechart\/AddRow\/Interceptor.php:23]\n#10 Magepow\\Sizechart\\Controller\\Adminhtml\\Sizechart\\AddRow\\Interceptor->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:111]\n#11 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:151]\n#12 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#13 Magepow\\Sizechart\\Controller\\Adminhtml\\Sizechart\\AddRow\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#14 Magepow\\Sizechart\\Controller\\Adminhtml\\Sizechart\\AddRow\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:145]\n#15 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#16 Magepow\\Sizechart\\Controller\\Adminhtml\\Sizechart\\AddRow\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#17 Magepow\\Sizechart\\Controller\\Adminhtml\\Sizechart\\AddRow\\Interceptor->___callPlugins() called at [generated\/code\/Magepow\/Sizechart\/Controller\/Adminhtml\/Sizechart\/AddRow\/Interceptor.php:32]\n#18 Magepow\\Sizechart\\Controller\\Adminhtml\\Sizechart\\AddRow\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:245]\n#19 Magento\\Framework\\App\\FrontController->getActionResponse() called at [vendor\/magento\/framework\/App\/FrontController.php:212]\n#20 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:147]\n#21 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#22 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#23 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#24 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:23]\n#25 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]\n#26 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:23]\n#27 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:264]\n#28 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:30]\n","url":"\/v4xsob1t\/magepow_sizechart\/sizechart\/addrow\/id\/1\/key\/261bd4758f5dbe79f71a53c9a90c3707f40ee4418c30aa2c57ebf6fa44075439\/","script_name":"\/pub\/index.php","report_id":"5953f71e149e4a6640d01f868b58a0bf3148ee4e52012e2f52c9b69189dcad67"}

**Comment by magiccart** [comment]
Hi, I have tested on PHP 8.1 but don't see error. If you need support check it please create a ticket here https://magepow.com/ticket/ or email to support@magepow.com and provide info our developer will check it for you

**Comment by TuVanDev** [comment]
@ticbitvax  @magiccart I've also had this issue in my local environment, although it does not occur on dev site.
So this issue occurs in some environments.

Step to reproduce the issue:
1. From the admin menu navigate to MagePow > Size Chart Management
2. Create a new size chart rule or edit an existing size chart rule.

There is a typo (case sensitive) caused this issue: https://github.com/magepow/magento-2-size-chart/blob/master/Controller/Adminhtml/Action.php#L43

`\Magepow\Sizechart\Model\sizechartFactory` should be changed to `\Magepow\Sizechart\Model\SizechartFactory`

**Comment by magiccart** [comment]
@Viper9x Thanks for the report! I will update it.
